version: "3.7"
services:
    fin-dep-parser-wrapper:
        build: .
        depends_on:
          - turku-neural-parser
        ports:
          - 5000:5000
        networks:
          seco:
            ipv4_address: "172.30.20.98"
        env_file:
          - docker.neural-parser.env
    turku-neural-parser:
        image: hsci/turku-neural-parser-openshift
        command: server fi_tdt parse_plaintext
        ports:
          - "7689:7689"
        networks:
          seco:
            ipv4_address: "172.30.20.97"
networks:
    seco:
      driver: "bridge"
      ipam:
        driver: "default"
        config:
          - subnet: "172.30.20.0/22"